WIFI_MODE = "AP" # AP or STA
WIFI_AP_PSK  = "12345678a"
WIFI_AP_SSID = "ESP32"
WIFI_STA_SSID = ""
WIFI_STA_PASSWORD = ""
IP_NETWORK  = "STATIC"  # STATIC or left blank for dynamic ip by DHCP
IPV4_ADDR   = "192.168.3.90"
IPV4_NETMASK= "255.255.255.0"
IPV4_GATEWAY= "192.168.3.3"